### PR TITLE
Update runtime to GNOME 44

### PR DESCRIPTION
**Pull request by orowith2os**

### CODE REVIEW

**Comment by orowith2os** [comment]
@D3SOX something's up with the upstream Soundux release, there isn't a release for 0.2.8. Want me to downgrade it to 0.2.7?

**Comment by D3SOX** [comment]
Yes it should be 0.2.7.

**Comment by hfiguiere** [comment]
> @D3SOX something's up with the upstream Soundux release, there isn't a release for 0.2.8. Want me to downgrade it to 0.2.7?

https://github.com/Soundux/Soundux/issues/670

**Comment by hfiguiere** [comment]
The webkit requirement is what prevent the update. GNOME 44 only ships 4.1 (because of libsoup)

**Comment by D3SOX** [comment]
Obsolete by #71

**Pull request closed without merging**
